name: dart_course
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  mocky: ^0.1.2
# path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
